apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
        app: todoapp
    spec:
      containers:
        - image: mohamedmagdykhamis/helm-nodeapp
          imagePullPolicy: Always
          name: myweb
          ports:
            - containerPort: 3001
          env:
            - name: "MONGO_URL"
              value: "mongodb://db-service/mydatabase"
            - name: "JWT_SECRET_KEY"
              value: "secretkey"
          resources:
            limits:
              memory: 500Mi
              cpu: 100m
            requests:
              memory: 250Mi
              cpu: 80m
